### ISSUE TITLE
Exception in thread "main" com.sun.jna.platform.win32.COM.COMException: Library not registered.(HRESULT: 8002801d)

### ISSUE THREAD

**Issue by tsatatwer** [matthiasblaesing/TlbCodeGenerator#5]
Trying to use the tool with COM object other than Word or Excel the com 
The object is presented in OLE/COM Viewer tool windows 10 :

![Untitled](https://github.com/matthiasblaesing/TlbCodeGenerator/assets/19878047/8fb2509e-fe7b-4485-8a16-bf2fa9dfde62)

```
Exception in thread "main" com.sun.jna.platform.win32.COM.COMException: Library not registered.(HRESULT: 8002801d)
        at com.sun.jna.platform.win32.COM.COMUtils.checkRC(COMUtils.java:117)
        at com.sun.jna.platform.win32.COM.TypeLibUtil.<init>(TypeLibUtil.java:96)
        at com.sun.jna.platform.win32.COM.tlb.TlbImp.<init>(TlbImp.java:82)
        at com.sun.jna.platform.win32.COM.tlb.TlbImp.main(TlbImp.java:67)
```

**Comment by matthiasblaesing** [comment]
What is missing from the issue report is (send via email):

```
java -cp "./*" com.sun.jna.platform.win32.COM.tlb.TlbImp -tlb.id  {F4D38EE0-30E9-45EA-B385-B2EDE310FBCD}  -tlb.major.version 1 -tlb.minor.version 0 -bind.mode dispId -output.dir outputdir_ascom
```

The screenshot does not show the type library enty, but a single object from it. So my claim: You got the wrong ID.

In "OLE/COM Viewer" choose "View -> Expert Mode" and Find the library under "Type Libraries". Either have a look at the right side of the window:

![image](https://github.com/matthiasblaesing/TlbCodeGenerator/assets/2179736/29e9efda-ec63-4b2e-8179-43ea30bee3a6)

or execute a double click on the entry and read uuid and version:

![image](https://github.com/matthiasblaesing/TlbCodeGenerator/assets/2179736/9e5da155-2274-4924-9654-17d741e35536)

**Comment by tsatatwer** [comment]
Hi Matthias,

**perfect the right answer it is indeed View -> Expert Mode ->Type Libraries**
 appreciated developments of JNA it is great tool  thanks for your great efforts   " vielen Dank"
