### ISSUE TITLE
Duplicate methods created and deprecated JNA  methods  used 

### ISSUE THREAD

**Issue by tsatatwer** [matthiasblaesing/TlbCodeGenerator#6]
Hi ,
while using this tool to generate code I encountered duplicate methods created and deprecated JNA methods  used check the following:

**Deprecated:**

 ```
/**
     * 
     * Virtual table id: 64
     * Member id: 1610743809
     */
    public BOOL Equals(VARIANT obj) {
        VARIANT.ByReference pResult = new VARIANT.ByReference();
        this.oleMethod(OleAuto.DISPATCH_METHOD, pResult, getIDispatch(), new DISPID(1610743809), new VARIANT[] {obj});
        return ((BOOL) pResult.getValue());
    }

    /**
     * 
     * Virtual table id: 72
     * Member id: 1610743810
     */
    public int GetHashCode() {
        VARIANT.ByReference pResult = new VARIANT.ByReference();
        this.oleMethod(OleAuto.DISPATCH_METHOD, pResult, getIDispatch(), new DISPID(1610743810), new VARIANT[] {});
        return ((int) pResult.getValue());
    }

```
The method oleMethod(int, Variant.VARIANT.ByReference, IDispatch, OaIdl.DISPID, Variant.VARIANT[]) from the type COMBindingBaseObject is deprecated

**Duplicate :**

```
 /**
     * 
     * Virtual table id: 56
      * Member id: 101
     */
    public short getBinX() {
        return (short)this._invokeNativeObject(7, new Object[] { this.getPointer() }, short.class);
    }
    
    
 /**
     * 
     * Virtual table id: 80
      * Member id: 1745027147
     */
    public short getBinX() {
        return (short)this._invokeNativeObject(7, new Object[] { this.getPointer() }, short.class);
    }

```
This method call :

```
 /**
     * 
     * Virtual table id: 176
     * Member id: 113
     */
    public void setConnected(BOOL connected) {
        this._invokeNativeInt(22, new Object[] { this.getPointer(), connected});
    }
```
    
    
And  this.getPointer() return NullPointerException although object class created with correct CSLID??

**Comment by matthiasblaesing** [comment]
This looks as this this is not generated by TlbCodeGenerator. This projects aims at the newstyle interface based binding. This is the old style, which matches the code generator in JNA iself.

**Comment by tsatatwer** [comment]
What's that mean ??? could you please explain more I am using JNA 5.13.0   com.sun.jna.platform.win32.COM.tlb.TlbImp using this  command :

` java -cp "./*" com.sun.jna.platform.win32.COM.tlb.TlbImp -tlb.id  {C6706DA9-C0D8-4473-9D93-8F4690960748}  -tlb.major.version 1 -tlb.minor.version 0  -output.dir new_camera`

**Comment by matthiasblaesing** [comment]
`com.sun.jna.platform.win32.COM.tlb.TlbImp` is not in this project, it is in JNA itself. `TlbCodeGenerator` generates code that uses the `com.sun.jna.platform.win32.COM.util` package (https://github.com/java-native-access/jna/tree/master/contrib/platform/src/com/sun/jna/platform/win32/COM/util), while `com.sun.jna.platform.win32.COM.tlb.TlbImp` generates code that uses the `com.sun.jna.platform.win32.COM`.
My personal advice: If you find an error, be prepared to fix it. `TlbCodeGenerator` was written because at time of inception I needed it at work. The Code generator does not write itself and it takes time and use-cases to investigate problems.

**Comment by tsatatwer** [comment]
Ok thanks for the support I will do that myself , I have already  have written the code to speak with CCD camera Telescope and other instruments using ASCOM and JNA , I have searched for an utility to map function of COM and .Net ASCOM drivers to java .
